# -*- coding: utf-8 -*-
"""accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8k3h-f-wugVeU4nPZdW6tlNzIwZuVWU
"""

from tensorflow.keras.models import load_model

# To load the entire model:
loaded_model = load_model('model.pkl')


test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")
